title: [Nikita Bhalla]
logo: "nikita.jpg"
github:
  is_project_page: false
description: > # your text below (remove <br> elements if you don't need line breaks)
  [ MS @ UMASS ]  
  <br><br>
  <a href="https://www.linkedin.com/in/nikitabhalla/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/nbhalla93">View My GitHub Profile</a>
  <br><br>
theme: jekyll-theme-minimal
